from lib.plots.comp.line import (curve, comparison, stack, twinx, twinx_comparison, scatter, comparison_stack)
from lib.plots.comp.bar import (bar)
from lib.plots.comp.func import (fpoints, fcurve, fscatter, fbar)
from lib.plots.comp.func import (fpoints, fcurve, fscatter, fbar)
from lib.plots.comp.surface import (contour,contour_hist)
from lib.plots.comp.axis import (PlotType)