from lib.plots.data import (curve, comparison, stack, twinx)
from lib.plots.func import (fpoints, fcurve)
from lib.plots.axis import (PlotType)
from lib.plots.reg import (single_var)
from lib.plots.hist import (bar, hist)
from lib.plots.hyp_test import (HypTestPlotType, htest)
